### ISSUE TITLE
Ollama填写地址成功调用后，但是仍出现404现象

### ISSUE THREAD

**Issue by Antony-Jia** [songquanpeng/one-api#1532]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用最新版本的one-api和ollama后，在测试接口时，后台ollama已经出现了调用成功的标志，但是显示仍然是404
**复现步骤**
使用WSL2 docker compose部署产品添加测试后出现问题。我使用的是Qwen2模型，docker compose文件如下

```
version: '3.1'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama:/root/.ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - aiwen-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]


  paradedb:
    image: paradedb/paradedb:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Replace with your actual username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Replace with your actual password
      POSTGRESQL_DATABASE: ${POSTGRES_DB}  # Replace with your desired database name
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - paradedb_data:/bitnami/postgresql
    ports:
      - "5432:5432"
    #restart: always  # Ensure the container restarts if it exits unexpectedly
    networks:
      - aiwen-network

  oneapi:
    container_name: oneapi
    image: one-api:latest
    ports:
      - 3000:3000
    depends_on:
      - paradedb
    networks:
      - aiwen-network
    # restart: always
    environment:
      # mysql 连接参数
      - SQL_DSN=postgres://postgres:${POSTGRES_PASSWORD}@paradedb:5432/oneapi
      # 登录凭证加密密钥
      - SESSION_SECRET=oneapikey
      # 内存缓存
      - MEMORY_CACHE_ENABLED=true
      # 启动聚合更新，减少数据交互频率
      # - BATCH_UPDATE_ENABLED=true
      # 聚合更新时长
      # - BATCH_UPDATE_INTERVAL=10
      # 初始化的 root 密钥（建议部署完后更改，否则容易泄露）
      - INITIAL_ROOT_TOKEN=aiwen
      - TZ=Asia/Shanghai
    volumes:
      - oneapi:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  aiwen-network:
    external: true
    name: aiwen-network

volumes:
  paradedb_data:
  ollama:
  oneapi:
```
**预期结果**

**相关截图**
![image](https://github.com/songquanpeng/one-api/assets/58219593/80b1b5a9-2b9a-4fc6-8919-7a7e4418742a)

如果没有的话，请删除此节。
