### ISSUE TITLE
多机部署，从节点会请求到未启用渠道

### ISSUE THREAD

**Issue by mrhaoji** [songquanpeng/one-api#199]
**例行检查**
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
渠道列表里面有多个渠道，但是已经禁用到只剩渠道 2
在“主节点”请求，每次返回都是渠道 2 的结果（从 header 分辨的）
但是“从节点”请求，会出现多种渠道返回的结果
已自行停止镜像、重启镜像、删除镜像多次，仍然是一样的情况
甚至将这个唯一启用渠道密钥故意改错后，出现“主节点”如预期一样无法请求，“从节点”仍有概率请求成功。

**复现步骤**
多机部署，添加多个可用渠道，禁用渠道只剩 1 个，并将该渠道密钥故意改错，在“从节点”发起请求观察结果

**预期结果**
主从节点渠道保持一致

主节点配置
```
version: '3.4'

services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=oneapi:oneapi@tcp(10.0.0.26:3306)/oneapi  # 修改此行，或注释掉以使用 SQLite 作为数据库
\#      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=asdfwegqewtqwet  # 修改为随机字符串
      - TZ=Asia/Shanghai
\#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
\#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
\#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行

    depends_on:
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk '{print $2}' | grep 'true'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always
```

从节点配置

```
version: '3.4'

services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=oneapi:oneapi@tcp(xxxxxxxx:#######)/oneapi  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=asdfwegqewtqwet  # 修改为随机字符串
      - TZ=Asia/Shanghai
      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
      - FRONTEND_BASE_URL=https://openai.mrhaoji.com  # 多机部署时从节点取消注释该行

    depends_on:
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk '{print $2}' | grep 'true'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always
```
