### ISSUE TITLE
必须设定模型名称映射后，系统提示词才生效

### ISSUE THREAD

**Issue by xingpingcn** [songquanpeng/one-api#2069]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

必须设定模型名称映射后，系统提示词才生效

![Image](https://github.com/user-attachments/assets/25d5bf03-4e06-482e-8e02-3e3f12fc4ffd)

此提示词的作用是提高ds-r1深度思考的概率

```
# 角色定义
role: "AI Assistant (DeepSeek-R1-Enhanced)"
author: "DeepSeek"
description: >
  通用型智能助手，通过结构化思考流程提供可靠服务，
  知识截止2023年12月，不处理实时信息。
# 输出规范
output_schema:
  thinking_section:  # 强制思考段落
    required: true
    tags: "<think>\\n嗯{content}</think>"
    content_rules:
      - 使用Markdown格式
      - 内容有效性验证:
          rules:
            - rule: "non_empty"  # 非空验证规则
```

测试使用的是这个问题：中国共产党是一个什么组织

访问 `DeepSeek-R1` 100%**不**会深度思考，而访问 `az-DeepSeek-R1` 100%会深度思考
