### ISSUE TITLE
支持通义千问

### ISSUE THREAD

**Issue by mrhaoji** [songquanpeng/one-api#326]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
接口文档 https://help.aliyun.com/document_detail/2399481.html

**应用场景**
增加通义千问渠道

**Comment by songquanpeng** [comment]
好像阿里这个支持一堆开源模型，有点意思

**Comment by songquanpeng** [comment]
已经支持

**Comment by mrhaoji** [comment]
通用文本向量 https://help.aliyun.com/document_detail/2399494.html

考虑支持一下？

**Comment by St-ZFeng** [comment]
![image](https://github.com/songquanpeng/one-api/assets/113660099/779042d1-2b60-4b41-addb-247561cb3413)
这个f返回形式有点奇怪，好像和其他平台的模型都不太一样？没有token计数啥的

**Comment by St-ZFeng** [comment]
> ![image](https://user-images.githubusercontent.com/113660099/260417631-779042d1-2b60-4b41-addb-247561cb3413.png) 这个返回形式有点奇怪，好像和其他平台的模型都不太一样？没有token计数啥的

哦哦，是啥SSE的问题......

**Comment by RedwindA** [comment]
请问调取的时候，仍然是以openai的格式调取吗？
我目前使用项目[LibreChat](https://github.com/danny-avila/LibreChat)中的`librechat.yaml`([相关配置文档](https://docs.librechat.ai/install/configuration/custom_config.html)），添加了一个阿里的端点：

```
    - name: "阿里"
      apiKey: "sk-xxx"
      baseURL: "https://api.my.site/api/v1"
      models:
        default: ["qwen-max","qwen-vl-max"]
        fetch: false
      titleConvo: true
      titleModel: "qwen-max"
      summarize: false
      summaryModel: "qwen-max"
      forcePrompt: false
      modelDisplayLabel: "阿里"
```
已经添加了一个阿里的渠道：
![1706585999917.png](https://image.redwind.top/i/2024/01/30/65b86f8b51b49.png)

但是使用该端点时报错如下
![1706586027744.png](https://image.redwind.top/i/2024/01/30/65b86fa71fd41.png)

所以我想问一下One API是否将阿里的转换为了OpenAI端点的格式？因为LibreChat只支持openai格式的
