### ISSUE TITLE
未提供令牌

### ISSUE THREAD

**Issue by SODAWater1** [songquanpeng/one-api#823]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
部署完成，获取到key之后到chatgpt-next-web使用，发现提示
{
  "error": {
    "message": "未提供令牌 (request id: 2023121511473370584704PNMYjJfX)",
    "type": "one_api_error"
  }
}
**复现步骤**
抓包发现请求包有带key的
**预期结果**
正常使用
**相关截图**
<img width="953" alt="截屏2023-12-15 11 51 59" src="https://github.com/songquanpeng/one-api/assets/129862877/8c9828c8-91b4-4528-9112-f06d990bf2ef">

**Comment by ye4293** [comment]
调用的格式错误了。要用openai的格式去调用

**Comment by songquanpeng** [comment]
你的渠道是什么类型的？

**Comment by DefensiveSniper** [comment]
无效的令牌
![image](https://github.com/songquanpeng/one-api/assets/105640670/a539b1d9-76b3-45e7-81c8-70cad251806f)
![image](https://github.com/songquanpeng/one-api/assets/105640670/e1570f16-a461-4d26-b03a-44698f78b99d)

**Comment by DefensiveSniper** [comment]
随后我在py测试了一下，依旧是无效的令牌
![image](https://github.com/songquanpeng/one-api/assets/105640670/4ac889b3-c3bf-4893-8712-d3d6813d1231)

**Comment by lizhuang** [comment]
要在one-api配置渠道里配置key,如sk-key-aaaaa，然后请求HEADS用Authorization: Bearer sk-key-aaaaa

**Comment by versatile712** [comment]
> 要在one-api配置渠道里配置key,如sk-key-aaaaa，然后请求HEADS用Authorization: Bearer sk-key-aaaaa

请问在没有部署服务器，只希望使用中转api服务的情况下，该如何配置渠道key呢？我看个人管理界面里没有渠道按钮

**Comment by LinuxSuRen** [comment]
我用 [linuxsuren/api-testing](https://github.com/linuxsuren/api-testing) 可以成功调用 chat 接口，配置如下：

```yaml
name: one-api
api: http://172.11.0.6:31448/
items:
  - name: login
    request:
      api: /api/user/login
      method: POST
      body: |-
        {
          "username": "root",
          "password": "123456"
        }
    expect:
      statusCode: 200
  - name: chat
    request:
      api: /v1/chat/completions
      method: POST
      header:
        Authorization: Bearer sk-g2kZSrUvd1CFL1fTE20eF552A2Af4b189f075cB02b8122Ab
        Content-Type: application/json
      body: |-
        {
          "messages": [
              {
                "content": "https://github.com/linuxsuren/api-testing",
                "role": "user"
              }
          ],
          "model": "chatglm_std"
        }
    expect:
      statusCode: 200
```
