### ISSUE TITLE
Kylin V10 Sp2 v2207高级服务器系统，docker启动最新one-api报错

### ISSUE THREAD

**Issue by xinaiwunai** [songquanpeng/one-api#834]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Kylin V10 Sp2 v2207高级服务器系统，拉取one-api项目中的docker-compose.yml, 启动最新one-api报错。
此前启动redis时候也遇到问题，最后确认时 redis:latest的容器与kylin系统版本不对，改用redis:bullseye 就可以了。
同样的问题在postgres和pgvector容器上也发生了。改用bullseye版本的镜像即可。
现在one-api容器遇到同样问题，但因错误提示不明显，还请项目组专家帮忙分析，看看是什么原因？

**复现步骤**
docker-compose up -d
docker logs one-api

**预期结果**
```bash
[root@localhost one-api]# uname -a
Linux localhost.localdomain 4.19.90-52.31.v2207.ky10.x86_64 #1 SMP Tue Nov 7 19:01:03 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost one-api]# docker -v
Docker version 20.10.23, build 7155243

[root@localhost one-api]# docker-compose -v
Docker Compose version v2.23.3

[root@localhost one-api]# docker image list
REPOSITORY                     TAG             IMAGE ID       CREATED        SIZE
justsong/one-api               latest          de350309a1b4   9 hours ago    38.4MB
codingone/pgvector             latest          d92cf9bfb445   12 hours ago   389MB
justsong/one-api               <none>          d0e7f3455340   13 hours ago   38.4MB
ghcr.io/labring/fastgpt-docs   latest          667a15f4dc10   2 days ago     114MB
mysql                          8.2.0           380f0456d1c1   5 days ago     619MB
ghcr.io/labring/fastgpt        latest          fe8afe98d0a4   5 days ago     330MB
redis                          latest          76506809a39f   13 days ago    138MB
postgres                       15.3-bullseye   7a6b3f65d388   4 months ago   379MB
mongo                          5.0.18          6e57b03e71ef   5 months ago   663MB
redis                          bullseye        9316221abf0d   6 months ago   117MB


[root@localhost one-api]# docker run justsong/one-api:latest
WARNING: IPv4 forwarding is disabled. Networking will not work.
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0xdaa62b m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0xdaa62b
stack: frame={sp:0x7ffe7d112730, fp:0x0} stack=[0x7ffe7c913bb0,0x7ffe7d112bc0)
0x00007ffe7d112630:  0x0000000000000000  0x00007ffe7d1126f8 
0x00007ffe7d112640:  0x0000000000e21370  0x000000001c000004 
0x00007ffe7d112650:  0x0000000000d978a0  0x0000000000000000 
0x00007ffe7d112660:  0x00007f188f84b1c0  0x0000000000000012 
0x00007ffe7d112670:  0x000000c000040000  0x000000c000066000 
0x00007ffe7d112680:  0x0000000000000000  0x0000000000000000 
0x00007ffe7d112690:  0x0000000000000000  0x0000000000000000 
0x00007ffe7d1126a0:  0x00007ffe7d112878  0x000000c000040000 
0x00007ffe7d1126b0:  0x00007ffe7d112898  0x0000000000dd9cbd 
0x00007ffe7d1126c0:  0x00007f1848ce96c0  0x00007ffe7d112940 
0x00007ffe7d1126d0:  0x00007ffe7d1127e6  0x0000000000000000 
0x00007ffe7d1126e0:  0x00007ffe7d1127e7  0x0000000000da89b0 
0x00007ffe7d1126f0:  0x00007f0000000000  0x0000000000000110 
0x00007ffe7d112700:  0x00000000003d0f00  0x0000000000dd77e4 
0x00007ffe7d112710:  0x00007f1848ce9990  0x000000000000000d 
0x00007ffe7d112720:  0x000000000178d8a0  0x0000000000daa61e 
0x00007ffe7d112730: <0x0000000000800300 <html/template.(*escaper).escapeList+0x0000000000000160>  0x99c18d3c73c68400 
0x00007ffe7d112740:  0x0000000000000006  0x0000000002d5b3c0 
0x00007ffe7d112750:  0x00007ffe7d112a00  0x0000000000000000 
0x00007ffe7d112760:  0x0000000001dfe560  0x0000000000d97832 
0x00007ffe7d112770:  0x0000000001e2ee40  0x00000000004013e1 
0x00007ffe7d112780:  0x0000000000000020  0x0000000001d95503 
0x00007ffe7d112790:  0x0000000000000828  0x0000000000da2261 
0x00007ffe7d1127a0:  0x0000000001df9960  0x0000000000000001 
0x00007ffe7d1127b0:  0x000000000000000a  0x0000000002d5b3c0 
0x00007ffe7d1127c0:  0x0000000000000000  0x0000000001dfe560 
0x00007ffe7d1127d0:  0x0000000000000006  0x0000000000da3b59 
0x00007ffe7d1127e0:  0x0000000001d95480  0x0000000000da4303 
0x00007ffe7d1127f0:  0x0000000001d95480  0x000000000000000a 
0x00007ffe7d112800:  0x0000000002d5b3c0  0x0000000000da1c0a 
0x00007ffe7d112810:  0x0000000001d95a08  0x99c18d3c73c68400 
0x00007ffe7d112820:  0x0000000001d95a08  0x0000000001d95a08 
runtime: g 0: unknown pc 0xdaa62b
stack: frame={sp:0x7ffe7d112730, fp:0x0} stack=[0x7ffe7c913bb0,0x7ffe7d112bc0)
0x00007ffe7d112630:  0x0000000000000000  0x00007ffe7d1126f8 
0x00007ffe7d112640:  0x0000000000e21370  0x000000001c000004 
0x00007ffe7d112650:  0x0000000000d978a0  0x0000000000000000 
0x00007ffe7d112660:  0x00007f188f84b1c0  0x0000000000000012 
0x00007ffe7d112670:  0x000000c000040000  0x000000c000066000 
0x00007ffe7d112680:  0x0000000000000000  0x0000000000000000 
0x00007ffe7d112690:  0x0000000000000000  0x0000000000000000 
0x00007ffe7d1126a0:  0x00007ffe7d112878  0x000000c000040000 
0x00007ffe7d1126b0:  0x00007ffe7d112898  0x0000000000dd9cbd 
0x00007ffe7d1126c0:  0x00007f1848ce96c0  0x00007ffe7d112940 
0x00007ffe7d1126d0:  0x00007ffe7d1127e6  0x0000000000000000 
0x00007ffe7d1126e0:  0x00007ffe7d1127e7  0x0000000000da89b0 
0x00007ffe7d1126f0:  0x00007f0000000000  0x0000000000000110 
0x00007ffe7d112700:  0x00000000003d0f00  0x0000000000dd77e4 
0x00007ffe7d112710:  0x00007f1848ce9990  0x000000000000000d 
0x00007ffe7d112720:  0x000000000178d8a0  0x0000000000daa61e 
0x00007ffe7d112730: <0x0000000000800300 <html/template.(*escaper).escapeList+0x0000000000000160>  0x99c18d3c73c68400 
0x00007ffe7d112740:  0x0000000000000006  0x0000000002d5b3c0 
0x00007ffe7d112750:  0x00007ffe7d112a00  0x0000000000000000 
0x00007ffe7d112760:  0x0000000001dfe560  0x0000000000d97832 
0x00007ffe7d112770:  0x0000000001e2ee40  0x00000000004013e1 
0x00007ffe7d112780:  0x0000000000000020  0x0000000001d95503 
0x00007ffe7d112790:  0x0000000000000828  0x0000000000da2261 
0x00007ffe7d1127a0:  0x0000000001df9960  0x0000000000000001 
0x00007ffe7d1127b0:  0x000000000000000a  0x0000000002d5b3c0 
0x00007ffe7d1127c0:  0x0000000000000000  0x0000000001dfe560 
0x00007ffe7d1127d0:  0x0000000000000006  0x0000000000da3b59 
0x00007ffe7d1127e0:  0x0000000001d95480  0x0000000000da4303 
0x00007ffe7d1127f0:  0x0000000001d95480  0x000000000000000a 
0x00007ffe7d112800:  0x0000000002d5b3c0  0x0000000000da1c0a 
0x00007ffe7d112810:  0x0000000001d95a08  0x99c18d3c73c68400 
0x00007ffe7d112820:  0x0000000001d95a08  0x0000000001d95a08 

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc000060740 sp=0xc000060730 pc=0x46b168
runtime.main()
	/usr/local/go/src/runtime/proc.go:169 +0x6d fp=0xc0000607e0 sp=0xc000060740 pc=0x43d68d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x46d141

rax    0x0
rbx    0x1
rcx    0xdaa62b
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x6
rsp    0x7ffe7d112730
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x7ffe7d112a00
r13    0x0
r14    0x1dfe560
r15    0x6
rip    0xdaa62b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0





```

**Comment by xinaiwunai** [comment]
dcoekr-compose.yml

```yaml
version: '3.4'

services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data/oneapi:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=oneapi:123456@tcp(db:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:bullseye
    container_name: redis
    restart: always

  db:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql  # 挂载目录，持久化存储
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai   # 设置时区
      MYSQL_ROOT_PASSWORD: 'OneAPI@justsong' # 设置 root 用户的密码
      MYSQL_USER: oneapi   # 创建专用用户
      MYSQL_PASSWORD: '123456'    # 设置专用用户密码
      MYSQL_DATABASE: one-api   # 自动创建数据库

```

**Comment by xinaiwunai** [comment]
已解决，通过添加启动参数 `--privileged=true`

```yml
services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    privileged: true
```
